### ISSUE TITLE
Issue with Attaching Files To Records

### ISSUE THREAD

**Issue by langeraad** [Dmitrii-Naumov/AcumaticaRESTAPIClientForCSharp#1]
I was attempting to use the generated code and noticed an issue with the File Attachment methods (I will show the 'Bill' endpoint but it seems like an issue throughout. 

        public void BillPutFile (List<string> ids, string filename)
        {
             BillPutFileWithHttpInfo(ids, filename);
        }

I dont quite see a way to pass any sort of byte array/stream/file data into any of the methods. Is there something I am missing?

**Comment by Dmitrii-Naumov** [comment]
I think you are looking at outdated code. 
Current code looks like that:
EntityAPI class
```
   public void PutFile(string id, string filename, byte[] content)
        {
            PutFileWithHttpInfo(new List<string>() { id }, filename, content);
        }
```
